"""add printers table

Revision ID: 024e414d2905
Revises: 665ca5ebe127
Create Date: 2026-09-13 19:57:51.971097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024e414d2905'
down_revision: Union[str, Sequence[str], None] = '665ca5ebe127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('machine_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printers_machine_code'), 'printers', ['machine_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printers_machine_code'), table_name='printers')
    op.drop_table('printers')
    # ### end Alembic commands ###
