"""add printer sessions table

Revision ID: c709ac96e955
Revises: 024e414d2905
Create Date: 2026-09-13 20:55:17.595627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c709ac96e955'
down_revision: Union[str, Sequence[str], None] = '024e414d2905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('printer_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_sessions_file_id'), 'printer_sessions', ['file_id'], unique=False)
    op.create_index(op.f('ix_printer_sessions_printer_id'), 'printer_sessions', ['printer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printer_sessions_printer_id'), table_name='printer_sessions')
    op.drop_index(op.f('ix_printer_sessions_file_id'), table_name='printer_sessions')
    op.drop_table('printer_sessions')
    # ### end Alembic commands ###
